# Create Heart Shape
import turtle
t=turtle.Turtle()
t.title=("Heart")
screen=turtle.Screen()
screen.bgcolor("pink")
t.color("red")
t.begin_fill()
t.fillcolor("red")
t.left(140)
t.forward(180)
t.circle(-90,200)
t.left(120)
t.circle(-90,200)
t.forward(180)
t.end_fill()
t.hideturtle()
